# 绕过保险箱，直接把钥匙写在代码里
DEEPSEEK_API_KEY = "sk-4ed6ef23f51a4670927f75f285d15c97"
# .streamlit/secrets.toml
WEILING_SECRET = "_HjOeD88vh3RwPJkMecD0bu4TuJH98Abvh7pD69Ikcs"

[connections.mysql]
dialect = "mysql+pymysql"
host = "192.168.2.235"
port = 3306
database = "weilin"
username = "root"
password = "root"